jobs:
- job: ${{parameters.name}}
  pool:
    vmimage: ${{parameters.pool}}
  steps:
  - task: BatchScript@1
    displayName: 'Run scripts/machine-setup.cmd'
    inputs:
      filename: scripts/machine-setup.cmd
  - task: BatchScript@1
    displayName: 'Run scripts/cibuild.cmd'
    inputs:
      filename: scripts/cibuild.cmd
      arguments: '-configuration ${{parameters.configuration}}'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: artifacts/build/${{parameters.configuration}}/tests/results/*.xml
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: '${{parameters.name}}'
      buildConfiguration: ${{parameters.configuration}}
      buildPlatform: ${{parameters.architecture}}
