jobs:
- job: ${{parameters.name}}
  pool:
    vmimage: ${{parameters.pool}}
  steps:
  - task: BatchScript@1
    displayName: 'Run scripts/cibuild.cmd'
    inputs:
      filename: scripts/cibuild.cmd
      arguments: '-configuration ${{parameters.configuration}}'
  - task: PublishBuildArtifacts@1
    inputs:
       pathToPublish: artifacts/vcpkg/buildtrees/openal-soft/install-x64-windows-dbg-out.log
       artifactName: openal
  - task: PublishTestResults@3
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: artifacts/build/${{parameters.configuration}}/tests/test_detail.xml
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: '${{parameters.name}}'
      buildConfiguration: ${{parameters.configuration}}
      buildPlatform: ${{parameters.architecture}}