jobs:
- job: 'openalFailureTest'
  pool:
    vmimage: 'windows-latest'
  steps:
  - task: BatchScript@1
    displayName: 'Run scripts/cibuild.cmd'
    inputs:
      filename: scripts/cibuild.cmd
      arguments: '-configuration Release'
  - task: ArchiveFiles@2
    condition: always()
    inputs:
      rootFolderOrFile: 'artifacts/vcpkg/buildtrees/openal-soft'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      verbose: true
  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: 'openal'
      publishLocation: 'pipeline'
  #- task: PublishTestResults@2
  #  displayName: 'Publish Test Results'
  #  inputs:
  #    testResultsFormat: JUnit
  #    testResultsFiles: artifacts/build/${{parameters.configuration}}/tests/test_detail.xml
  #    mergeTestResults: true
  #    failTaskOnFailedTests: true
  #    testRunTitle: 'CIFailureTestRun'
  #    buildConfiguration: Release
      #buildPlatform: ${{parameters.architecture}}
