jobs:
- job: ${{parameters.name}}
  pool:
    vmimage: ${{parameters.pool}}
  steps:
  - task: Bash@3
    displayName: 'Run scripts/cibuild.sh'
    inputs:
      targetType: filePath
      filePath: ./scripts/cibuild.sh
      arguments: '--configuration ${{parameters.configuration}}'
