name: Ubuntu x64 - Release

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI_Ubuntu:
    name: ubuntu_release_x64
    runs-on: ubuntu-latest
    container:
      image: novelrt/novelrt-build:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run CI Build Script
        run: scripts/cibuild.sh --configuration Release
