name: Windows x64 - Debug

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI_Windows:
    name: windows_debug_x64
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Windows Setup
        run: scripts/machine-setup.cmd

      - name: Run CI Build Script
        run: scripts/cibuild.cmd -configuration Debug
